name: Build and Deploy
on:
    push:
        branches:
            - develop

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@master

            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3.6'

            -   name: Install Packages
                run: composer install --no-dev

            -   name: Deploy to Server
                uses: charliex2/laravel-action@master
                with:
                    user: ${{ secrets.SSH_USER }}
                    host: ${{ secrets.SSH_HOST }}
                    path: ${{ secrets.DEPLOY_PATH_HOMOLOGACAO }}
                    owner: $${{ secrets.SSH_USER }}
                    commands: |
                        php artisan migrate --seed --force
                        php artisan queue:restart
                        php artisan reverb:restart
                env:
                    DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
